apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-resources
  namespace: argocd
spec:
  project: product-api
  source:
    repoURL: https://github.com/tahalaina/product-api-gitops.git
    targetRevision: main
    path: observability/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
    syncOptions: [CreateNamespace=true]
