apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-metrics
  namespace: argocd
spec:
  project: product-api
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 89.2.0
    helm:
      releaseName: monitoring
      values: |
        alertmanager:
          enabled: true
        grafana:
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: ALL
          additionalDataSources:
            - name: Loki
              uid: loki
              type: loki
              access: proxy
              url: http://loki-gateway.observability.svc.cluster.local
            - name: Tempo
              uid: tempo
              type: tempo
              access: proxy
              url: http://tempo.observability.svc.cluster.local:3200
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {memory: 256Mi}
        prometheus:
          prometheusSpec:
            retention: 2d
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            resources:
              requests: {cpu: 200m, memory: 512Mi}
              limits: {memory: 1Gi}
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: [ReadWriteOnce]
                  resources:
                    requests: {storage: 2Gi}
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
