apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-traces
  namespace: argocd
spec:
  project: product-api
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.24.4
    helm:
      releaseName: tempo
      values: |
        tempo:
          retention: 24h
          reportingEnabled: false
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits: {memory: 512Mi}
        persistence:
          enabled: true
          size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
