apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-api
  namespace: argocd
spec:
  description: Product API GitOps applications
  sourceRepos:
    - https://github.com/tahalaina/product-api-gitops.git
  destinations:
    - namespace: product-api-dev
      server: https://kubernetes.default.svc
    - namespace: product-api-staging
      server: https://kubernetes.default.svc
    - namespace: product-api-production
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
