apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product-api
  namespace: argocd
spec:
  description: Product API GitOps applications and observability platform
  sourceRepos:
    - https://github.com/tahalaina/product-api-gitops.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
  destinations:
    - namespace: product-api-dev
      server: https://kubernetes.default.svc
    - namespace: product-api-staging
      server: https://kubernetes.default.svc
    - namespace: product-api-production
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
