apiVersion: v1
kind: Service
metadata:
  name: product-api
  labels:
    app.kubernetes.io/name: product-api
    app.kubernetes.io/part-of: product-api
spec:
  selector: {app: product-api}
  ports: [{port: 80, targetPort: http, name: http}]
